FROM python:3.7-buster
MAINTAINER silenceshell <silenceshell@datastart.cn>
RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
RUN mkdir -p /fcs
CMD ["/bin/sh", "-c", "sleep 360000"]
