FROM python:3.7-buster
MAINTAINER silenceshell <silenceshell@datastart.cn>
RUN mkdir -p /fcs \ 
    && apt-get update && apt-get install -y --no-install-recommends \
		vi \
CMD ["/bin/sh", "-c", "sleep 360000"]
